bap: skip bap_data without service when managing CIGs
If there is no service, we are not BAP Client for the session.

Because handling lifetime of devices is tied to the service, the
data->device pointer may be invalid when there is no service and remote
device was removed.

Fixes UAF of btd_device after a temporary device is removed (remote
device was sometimes BAP Client and other times Server).

Log:
==============================================
src/shared/gatt-server.c:handle_read_req() Read Req - handle: 0x006d
src/shared/gatt-server.c:read_complete_cb() Read Complete: err 0
src/shared/att.c:can_read_data() (chan 0x7bb28f7fb610) ATT PDU received: 0x0a
src/shared/gatt-server.c:handle_read_req() Read Req - handle: 0x007d
profiles/audio/bass.c:bap_attached() 0x7c428f7f6340
profiles/audio/bap.c:bap_attached() 0x7c428f7f6340
profiles/audio/bap.c:bap_data_add() data 0x7bf28f812ce0
... no corresponding bap_data_remove() ...
src/adapter.c:adapter_remove_connection() Removing temporary device /org/bluez/hci0/dev_AA_AA_AA_AA_AA_AA
src/device.c:device_remove() Removing device /org/bluez/hci0/dev_AA_AA_AA_AA_AA_AA
... no corresponding bap_data_remove() ...
ERROR: AddressSanitizer: heap-use-after-free
READ of size 8 at 0x7cb28f7e4800 thread T0
    #0 0x000000754216 in device_get_adapter src/device.c:6546
    #1 0x000000570f8e in find_cig_session profiles/audio/bap.c:2323
        (gdb: session == 0x7bf28f812ce0)
    #2 0x000000833f77 in queue_find src/shared/queue.c:230
    #3 0x000000571958 in find_cig_enumerate profiles/audio/bap.c:2362
    #4 0x000000573980 in bap_update_cigs_cb profiles/audio/bap.c:2511
    #5 0x7f4291d64e3c in g_idle_dispatch
freed by thread T0 here:
    #2 0x000000715eb0 in device_free src/device.c:962
    #3 0x000000813f1b in remove_interface gdbus/object.c:742
    #4 0x00000081c15d in g_dbus_unregister_interface gdbus/object.c:1499
    #5 0x000000760ba8 in btd_device_unref src/device.c:7763
    #6 0x0000007456d0 in device_remove src/device.c:5310
    #7 0x00000066cfe2 in btd_adapter_remove_device src/adapter.c:1458
    #8 0x0000006ad743 in adapter_remove_connection src/adapter.c:7619
    #9 0x0000006b8c15 in dev_disconnected src/adapter.c:8598
==============================================